server:
  port: 8521
spring:
  application:
    name: spring-cloud-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        register: false    #设置不需要注册到 consul 中
        serviceName: ${spring.application.name}    #注册到consul的服务
  zipkin:
      base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
#ribbon 负载均衡策略配置, service-producer为注册的服务名
service-producer:
  ribbon:
    #随机模式
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #轮询模式（默认）
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#开启熔断器
feign:
  hystrix:
    enabled: true