server:
  port: 8541
spring:
  application:
    name: spring-cloud-consul-zuul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}    # 注册到consul的服务名称
#zuul:
##  prefix: /v1
#  routes:
#    ribbon:
#      path: /ribbon/**
#      serviceId: spring-cloud-consul-consumer  # 转发到消费者 /ribbon/
#    feign:
#      path: /feign/**
#      serviceId: spring-cloud-consul-consumer  # 转发到消费者 /feign/