server:
  port: 8551
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shitongtong/spring-cloud-study2         # 配置git仓库的地址
          search-paths: config-reposity                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          #不用真实帐号也可以获取配置，不过相对有点慢
          username: username                                          # git仓库的账号
          password: password                                          # git仓库的密码